WELCOME_OFF: true
ASSUME_CUTS_CANNOT_CREATE_NEW_CONCEPTS: false
CUT_ONE_APPROXIMATION: false
MEASURE: EMD
PARTITION_TYPE: BI
PICK_SMALLEST_PURVIEW: false
USE_SMALL_PHI_DIFFERENCE_FOR_CES_DISTANCE: false
SYSTEM_CUTS: 3.0_STYLE
SINGLE_MICRO_NODES_WITH_SELFLOOPS_HAVE_PHI: false
VALIDATE_SUBSYSTEM_STATES: true
VALIDATE_CONDITIONAL_INDEPENDENCE: true
PARALLEL_CONCEPT_EVALUATION: false
PARALLEL_CUT_EVALUATION: false
PARALLEL_COMPLEX_EVALUATION: false
NUMBER_OF_CORES: -1
MAXIMUM_CACHE_MEMORY_PERCENTAGE: 50
CACHE_SIAS: false
CACHE_REPERTOIRES: true
CACHE_POTENTIAL_PURVIEWS: true
CLEAR_SUBSYSTEM_CACHES_AFTER_COMPUTING_SIA: false
CACHING_BACKEND: fs
FS_CACHE_VERBOSITY: 0
FS_CACHE_DIRECTORY: __pyphi_cache__
MONGODB_CONFIG:
    host: localhost
    port: 27017
    database_name: pyphi
    collection_name: cache
REDIS_CACHE: false
REDIS_CONFIG:
    host: localhost
    port: 6379
    db: 0
    test_db: 1
LOG_STDOUT_LEVEL: WARNING
LOG_FILE_LEVEL: INFO
LOG_FILE: pyphi.log
PROGRESS_BARS: true
REPR_VERBOSITY: 2
PRINT_FRACTIONS: true
PRECISION: 6